-- MySQL Script generated by MySQL Workbench
-- Sun Apr  2 13:32:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CucStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CucStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CucStore` DEFAULT CHARACTER SET utf8 ;
USE `CucStore` ;

-- -----------------------------------------------------
-- Table `CucStore`.`TUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CucStore`.`TUsuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correoUdg` VARCHAR(255) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `imgUrl` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CucStore`.`TCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CucStore`.`TCategoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `categoria_UNIQUE` (`categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CucStore`.`TProductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CucStore`.`TProductos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT(100) NOT NULL,
  `precio` FLOAT NOT NULL,
  `puntaje` FLOAT NOT NULL,
  `TUsuarios_id` INT NOT NULL,
  `TCategoria_id` INT NOT NULL,
  `imgUrl` VARCHAR(45)  NULL,
  PRIMARY KEY (`Id`, `TUsuarios_id`, `TCategoria_id`),
  INDEX `fk_TArticulos_TUsuarios_idx` (`TUsuarios_id` ASC) VISIBLE,
  INDEX `fk_TArticulos_TCategoria1_idx` (`TCategoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_TArticulos_TUsuarios`
    FOREIGN KEY (`TUsuarios_id`)
    REFERENCES `CucStore`.`TUsuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TArticulos_TCategoria1`
    FOREIGN KEY (`TCategoria_id`)
    REFERENCES `CucStore`.`TCategoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CucStore`.`TRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CucStore`.`TRoles` (
  `IdTRoles` INT NOT NULL AUTO_INCREMENT,
  `Rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CucStore`.`TRoles_has_TUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CucStore`.`TRoles_has_TUsuarios` (
  `TRoles_IdTRoles` INT NOT NULL,
  `TUsuarios_idTUsuarios` INT NOT NULL,
  PRIMARY KEY (`TRoles_IdTRoles`, `TUsuarios_idTUsuarios`),
  INDEX `fk_TRoles_has_TUsuarios_TUsuarios1_idx` (`TUsuarios_idTUsuarios` ASC) VISIBLE,
  INDEX `fk_TRoles_has_TUsuarios_TRoles1_idx` (`TRoles_IdTRoles` ASC) VISIBLE,
  CONSTRAINT `fk_TRoles_has_TUsuarios_TRoles1`
    FOREIGN KEY (`TRoles_IdTRoles`)
    REFERENCES `CucStore`.`TRoles` (`IdTRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRoles_has_TUsuarios_TUsuarios1`
    FOREIGN KEY (`TUsuarios_idTUsuarios`)
    REFERENCES `CucStore`.`TUsuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CucStore`.`TTelefonoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CucStore`.`TTelefonoUsuario` (
  `id` INT NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `TUsuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `TUsuarios_id`),
  INDEX `fk_TTelefonoUsuario_TUsuarios1_idx` (`TUsuarios_id` ASC) VISIBLE,
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE,
  CONSTRAINT `fk_TTelefonoUsuario_TUsuarios1`
    FOREIGN KEY (`TUsuarios_id`)
    REFERENCES `CucStore`.`TUsuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CucStore`.`TMensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CucStore`.`TMensajes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enviador_id` INT NOT NULL,
  `recibido_id` VARCHAR(45) NOT NULL,
  `mensaje` TEXT(280) NOT NULL,
  `creación` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `creación_UNIQUE` (`creación` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CucStore`.`TUsuarios_has_TMensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CucStore`.`TUsuarios_has_TMensajes` (
  `TUsuarios_id` INT NOT NULL,
  `TMensajes_id` INT NOT NULL,
  PRIMARY KEY (`TUsuarios_id`, `TMensajes_id`),
  INDEX `fk_TUsuarios_has_TMensajes_TMensajes1_idx` (`TMensajes_id` ASC) VISIBLE,
  INDEX `fk_TUsuarios_has_TMensajes_TUsuarios1_idx` (`TUsuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_TUsuarios_has_TMensajes_TUsuarios1`
    FOREIGN KEY (`TUsuarios_id`)
    REFERENCES `CucStore`.`TUsuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TUsuarios_has_TMensajes_TMensajes1`
    FOREIGN KEY (`TMensajes_id`)
    REFERENCES `CucStore`.`TMensajes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
